name: My 2 bits in cyberspace
description: Itsec, web dev and generally shitpoasting
meta_description: "Itsec, web dev and generally shitpoasting"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
logo: false
paginate: 15
baseurl: /
permalink: /:year/:month/:day/:title/
domain_name: 'https://herrbengtsson.github.com'
google_analytics: 'UA-88402567-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Axel'
