name: My 2 bits in cyberspace
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
logo: false
paginate: 15
baseurl: /
permalink: /:year/:month/:day/:title/
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Axel'
